import { test, expect } from '@playwright/test'

test('create, edit, refresh, complete and archive persisted tasks', async ({page}) => {
  await page.goto('/')
  await page.getByRole('button', {name: 'Create task', exact: true}).click()
  const editor = page.getByRole('dialog')
  await editor.getByLabel('Task name').fill('Study TypeScript')
  await editor.getByLabel('Task type').selectOption('reading')
  await editor.getByLabel('Notes').fill('Read chapter 1')
  await editor.getByLabel('Previously worked hours').fill('15')
  await editor.getByRole('button', {name: 'Create task', exact: true}).click()
  await expect(page.getByRole('heading', {name:'Study TypeScript'})).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', {name:'Study TypeScript'})).toBeVisible()
  await page.getByRole('button', {name:'Edit Study TypeScript',exact:true}).click()
  await page.getByLabel('Task name').fill('Learn TypeScript')
  await page.getByLabel('Previously worked hours').fill('63')
  await page.getByRole('button', {name:'Save changes'}).click()
  await expect(page.getByText('Hours worked: 63:00:00')).toBeVisible()
  await page.getByRole('button', {name:'Complete Learn TypeScript',exact:true}).click()
  await page.getByRole('button', {name:/^Completed/}).click()
  await expect(page.getByRole('heading', {name:'Learn TypeScript'})).toBeVisible()
  await page.getByRole('button', {name:'Archive Learn TypeScript',exact:true}).click()
  await page.getByRole('button', {name:/^Archived/}).click()
  await expect(page.getByText('Read chapter 1')).toBeVisible()
  await page.reload()
  await page.getByRole('button', {name:/^Archived/}).click()
  await expect(page.getByRole('heading', {name:'Learn TypeScript'})).toBeVisible()
  await expect(page.getByRole('button', {name:'Edit Learn TypeScript',exact:true})).toHaveCount(0)
})

test('failed transaction leaves editor open, shows error and persists no task', async ({page}) => {
  await page.addInitScript(() => {
    const add = IDBObjectStore.prototype.add
    IDBObjectStore.prototype.add = function(value, key) {
      const request = key === undefined ? add.call(this, value) : add.call(this, value, key)
      this.transaction.abort()
      return request
    }
  })
  await page.goto('/')
  await page.getByRole('button', {name:'Create task',exact:true}).click()
  await page.getByLabel('Task name').fill('Must not save')
  await page.getByRole('dialog').getByRole('button', {name:'Create task',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('not saved')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', {name:'Cancel'}).click()
  await expect(page.getByRole('heading',{name:'Must not save'})).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('heading',{name:'Must not save'})).toHaveCount(0)
})

test('invalid whitespace name is rejected and dialog restores focus on cancel', async ({page}) => {
  await page.goto('/')
  const create = page.getByRole('button', {name:'Create task',exact:true})
  await create.click()
  await page.getByLabel('Task name').fill('   ')
  await page.getByRole('dialog').getByRole('button', {name:'Create task',exact:true}).click()
  await expect(page.getByRole('alert')).toContainText('task name')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(create).toBeFocused()
})

test('narrow viewport has no horizontal overflow', async ({page}) => {
  await page.setViewportSize({width:375,height:812})
  await page.goto('/')
  await page.getByRole('button', {name:'Create task',exact:true}).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(375)
})

test('stale edit from another tab cannot overwrite a newer task', async ({page,context}) => {
  await page.goto('/')
  await page.getByRole('button',{name:'Create task',exact:true}).click()
  await page.getByLabel('Task name').fill('Shared task')
  await page.getByRole('dialog').getByRole('button',{name:'Create task',exact:true}).click()
  await page.getByRole('button',{name:'Edit Shared task',exact:true}).click()
  const other = await context.newPage()
  await other.goto('/')
  await other.getByRole('button',{name:'Edit Shared task',exact:true}).click()
  await other.getByLabel('Task name').fill('Updated elsewhere')
  await other.getByRole('button',{name:'Save changes'}).click()
  await expect(other.getByRole('heading',{name:'Updated elsewhere'})).toBeVisible()
  await page.getByLabel('Task name').fill('Stale overwrite')
  await page.getByRole('button',{name:'Save changes'}).click()
  await expect(page.getByRole('alert')).toContainText('another tab')
  await page.getByRole('button',{name:'Cancel'}).click()
  await page.getByRole('button',{name:'Refresh list'}).click()
  await expect(page.getByRole('heading',{name:'Updated elsewhere'})).toBeVisible()
  await expect(page.getByRole('heading',{name:'Stale overwrite'})).toHaveCount(0)
})

test('unavailable storage shows a recoverable error without claiming success', async ({page}) => {
  await page.addInitScript(() => { Object.defineProperty(window, 'indexedDB', {value: undefined}) })
  await page.goto('/')
  await expect(page.getByRole('alert')).toContainText('storage is unavailable')
  await expect(page.getByRole('button',{name:'Create task',exact:true})).toBeDisabled()
  await expect(page.getByRole('button',{name:'Retry loading'})).toBeVisible()
})

 test('periodic, inactivity and grace preferences persist independently', async ({page}) => {
  await page.goto('/')
  await page.getByRole('button',{name:'Create task',exact:true}).click()
  await page.getByLabel('Task name').fill('Presence settings')
  await page.getByText('Confirmation settings',{exact:true}).click()
  await page.getByLabel('Enable periodic confirmation').check()
  await page.getByLabel('Periodic interval (minutes)',{exact:true}).fill('30')
  await page.getByLabel('Inactivity interval (minutes)',{exact:true}).fill('10')
  await page.getByLabel('Grace period (minutes)',{exact:true}).fill('2')
  await page.getByRole('dialog').getByRole('button',{name:'Create task',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Presence settings',exact:true})).toBeVisible()
  await page.reload()
  await page.getByRole('button',{name:'Edit Presence settings',exact:true}).click()
  await page.getByText('Confirmation settings',{exact:true}).click()
  await expect(page.getByLabel('Periodic interval (minutes)',{exact:true})).toHaveValue('30')
  await expect(page.getByLabel('Inactivity interval (minutes)',{exact:true})).toHaveValue('10')
  await expect(page.getByLabel('Grace period (minutes)',{exact:true})).toHaveValue('2')
})
